default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  aliases: true

development:
  <<: *default
  database: db/development.sqlite3
  aliases: true

test:
  <<: *default
  database: db/test.sqlite3
  aliases: true

production:
  <<: *default
  database: db/production.sqlite3
  aliases: true
